server:
  port: 9191
  servlet:
    context-path: /profile

spring:
  config:
    import: "secrets.yml"
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${spring.neo4j.authentication.password}