server:
  port: 9191
  servlet:
    context-path: /v1/profile

spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${spring.neo4j.authentication.password}

spring.config.import: secrets.yml