name: Java CI with Maven

on:
  push:
    branches: [ "**" ]  # This will trigger for all branches
    paths:
      - release/**  # This will restrict the trigger to changes in the release directory
  pull_request:
    branches: [ "**" ]  # This will trigger for all branches in pull requests
    paths:
      - release/**  # This will restrict the trigger to pull requests that affect the release directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Inject Secrets
      run: |
        echo 'Injecting secrets.yml'
        echo "${{ secrets.PROFILE_SERVICE_SECRETS }}" > src/main/resources/secrets.yml

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Test with Maven
      run: mvn test --file pom.xml
