name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
https://github.com/HospitalMgmtService/profile-service

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Inject Secrets
      run: |
        echo 'Injecting secrets.yml'
        cp ${{ secrets.PROFILE_SERVICE_SECRETS }} src/main/resources/secrets.yml

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Test with Maven
      run: mvn test --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
